#!/bin/bash

# Why Mewtwo in as a package manger translator

# Mewtwo is rarely referred to as a "clone" in Japanese sources and also which means " Second of Mew " reffer Pokémon
# Mewtwo is a Pokémon that was created by genetic manipulation.

# what it will do ?
# use mew for translating plus a easy peasy pacage manager

echo "still in development here is a mewtwo"


# for mew will be deleted later
# mew home is tree of beggining
# mew is also taken as creator or ancestor of all Pokémons

echo "Mew - μ"

echo "Mewtwo - μ2"

read x
if
x = apt

pac =x

fi
